"""add audio_chunk_keys and frame_keys to job_parts

Revision ID: 287e2a945c07
Revises: d02b6a113486
Create Date: 2026-07-31 14:34:17.061897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '287e2a945c07'
down_revision: Union[str, None] = 'd02b6a113486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_parts', sa.Column('audio_chunk_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_parts', sa.Column('frame_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_parts', 'frame_keys')
    op.drop_column('job_parts', 'audio_chunk_keys')
    # ### end Alembic commands ###
